<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>AcademicPublishing.Contracts</PackageId>
    <Version>1.0.0</Version>
    <Authors>Yzeir Baku</Authors>
    <Description>Shared contracts and DTOs for AcademicPublishing API</Description>
  </PropertyGroup>

</Project>
